# Generated by Django 2.2.7 on 2020-09-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0002_auto_20200902_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khata',
            old_name='unique_id',
            new_name='order_id',
        ),
    ]
