# Generated by Django 2.2.7 on 2020-09-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0003_auto_20200902_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khata',
            name='order_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
