# Generated by Django 2.2.7 on 2020-09-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0004_auto_20200902_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('unique_id', models.CharField(max_length=20)),
                ('give', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='khata',
            name='get',
        ),
        migrations.RemoveField(
            model_name='khata',
            name='give',
        ),
        migrations.DeleteModel(
            name='Get',
        ),
        migrations.DeleteModel(
            name='Give',
        ),
    ]
