# Generated by Django 2.2.7 on 2020-09-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0005_auto_20200902_2131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoive',
            new_name='Invoice',
        ),
    ]
