# Generated by Django 2.2.7 on 2020-04-22 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='owner',
            new_name='vendor',
        ),
    ]
