# Generated by Django 2.2.7 on 2020-04-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0002_auto_20200414_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='main_category',
            field=models.CharField(choices=[('Shop', 'Shop'), ('Manufacturer', 'Manufacturer'), ('Service', 'Service')], default='sh', max_length=20),
        ),
    ]
