# Generated by Django 2.2.7 on 2020-04-22 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0003_auto_20200414_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='owner',
            new_name='vendor',
        ),
    ]
