# Generated by Django 2.2.7 on 2020-08-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vendor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
