# Generated by Django 2.2.7 on 2020-08-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_user_is_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_vendor',
        ),
    ]
