# Generated by Django 2.2.7 on 2020-04-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='main_category',
            field=models.CharField(choices=[('Shop', 'Shop'), ('Manufacturer', 'Manufacturer'), ('Service', 'Service')], default='sh', max_length=20),
        ),
    ]
