# Generated by Django 2.2.7 on 2020-04-22 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200415_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='owner',
            new_name='vendor',
        ),
    ]
