# Generated by Django 2.2.7 on 2020-07-28 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_user_is_admin'),
        ('shop', '0003_auto_20200421_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholeSeller',
            fields=[
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=shop.models.upload_image_path)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shop',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='shop',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ShopSubCategory',
        ),
    ]
