# Generated by Django 2.2.7 on 2020-08-08 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0004_auto_20200728_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_loaction', models.CharField(blank=True, max_length=255, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('order_id', models.CharField(blank=True, max_length=20, null=True)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.Shop')),
            ],
        ),
    ]
