# Generated by Django 2.2.7 on 2020-08-25 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200825_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='time',
            new_name='timestamp',
        ),
    ]
