# Generated by Django 2.2.7 on 2020-09-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_shoporder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporder',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
