# Generated by Django 2.2.7 on 2020-05-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icst',
            field=models.CharField(default='90 Minutes', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='ocst',
            field=models.CharField(choices=[('2 day', '2 day'), ('2 days', '2 days'), ('3 days', '3 days'), ('4 days', '4 days'), ('5 days', '5 days'), ('6 days', '6 days'), ('7 days', '7 days')], default='1 day', max_length=10),
        ),
    ]
