# Generated by Django 2.2.7 on 2020-09-09 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200827_1222'),
        ('products', '0006_auto_20200827_1333'),
    ]

    operations = [
    ]
